# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.coordinate import Coordinate
from swagger_server import util


class Area(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, coordinates: List[Coordinate]=None):  # noqa: E501
        """Area - a model defined in Swagger

        :param coordinates: The coordinates of this Area.  # noqa: E501
        :type coordinates: List[Coordinate]
        """
        self.swagger_types = {
            'coordinates': List[Coordinate]
        }

        self.attribute_map = {
            'coordinates': 'coordinates'
        }

        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'Area':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Area of this Area.  # noqa: E501
        :rtype: Area
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coordinates(self) -> List[Coordinate]:
        """Gets the coordinates of this Area.


        :return: The coordinates of this Area.
        :rtype: List[Coordinate]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: List[Coordinate]):
        """Sets the coordinates of this Area.


        :param coordinates: The coordinates of this Area.
        :type coordinates: List[Coordinate]
        """

        self._coordinates = coordinates
