# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FoundTreasure(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, index: float=None, proof: str=None):  # noqa: E501
        """FoundTreasure - a model defined in Swagger

        :param index: The index of this FoundTreasure.  # noqa: E501
        :type index: float
        :param proof: The proof of this FoundTreasure.  # noqa: E501
        :type proof: str
        """
        self.swagger_types = {
            'index': float,
            'proof': str
        }

        self.attribute_map = {
            'index': 'index',
            'proof': 'proof'
        }

        self._index = index
        self._proof = proof

    @classmethod
    def from_dict(cls, dikt) -> 'FoundTreasure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FoundTreasure of this FoundTreasure.  # noqa: E501
        :rtype: FoundTreasure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self) -> float:
        """Gets the index of this FoundTreasure.


        :return: The index of this FoundTreasure.
        :rtype: float
        """
        return self._index

    @index.setter
    def index(self, index: float):
        """Sets the index of this FoundTreasure.


        :param index: The index of this FoundTreasure.
        :type index: float
        """

        self._index = index

    @property
    def proof(self) -> str:
        """Gets the proof of this FoundTreasure.


        :return: The proof of this FoundTreasure.
        :rtype: str
        """
        return self._proof

    @proof.setter
    def proof(self, proof: str):
        """Sets the proof of this FoundTreasure.


        :param proof: The proof of this FoundTreasure.
        :type proof: str
        """

        self._proof = proof
