---
swagger: "2.0"
info:
  description: "This is a tresure hunt server"
  version: "1.0.0"
  title: "Treasure Hunt"
host: "teasure-hunt.herokuapp.com"
basePath: "/v1"
tags:
- name: "game"
  description: "Everything about games"
- name: "user"
  description: "Operations about user"
schemes:
- "https"
- "http"
paths:
  /game:
    get:
      tags:
      - "game"
      summary: "Get games"
      description: "Returns all games if no id is given"
      operationId: "get_games"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Game"
        "400":
          description: "Invalid"
        "403":
          description: "Forbidden access"
        "404":
          description: "Game not found"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
    post:
      tags:
      - "game"
      summary: "Add a game"
      description: ""
      operationId: "add_game"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Game that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Game"
      responses:
        "403":
          description: "Forbidden access"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
    put:
      tags:
      - "game"
      summary: "Update an existing game"
      description: ""
      operationId: "update_game"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Game that need to be put in the treasure hunt game"
        required: true
        schema:
          $ref: "#/definitions/Game"
      responses:
        "400":
          description: "Invalid ID supplied"
        "403":
          description: "Forbidden access"
        "404":
          description: "Game not found"
        "405":
          description: "Validation exception"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
    delete:
      tags:
      - "game"
      summary: "Get games"
      description: "Deletes a game"
      operationId: "delete_games"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid"
        "403":
          description: "Forbidden access"
        "404":
          description: "Game not found"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /game/findByActive:
    get:
      tags:
      - "game"
      summary: "Finds Games by active status"
      description: ""
      operationId: "find_games_by_active"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - name: "active"
        in: "query"
        description: "Active value that need to be considered for filter"
        required: true
        type: "boolean"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Game"
        "400":
          description: "Invalid active value"
        "403":
          description: "Forbidden access"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /game/findByUser:
    get:
      tags:
      - "game"
      summary: "Finds Games by user"
      description: ""
      operationId: "find_games_by_user"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Game"
        "400":
          description: "Invalid user value"
        "403":
          description: "Forbidden access"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /game/reset:
    get:
      tags:
      - "game"
      summary: "Reset game by ID"
      description: "Returns a reset game"
      operationId: "reset_game_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        description: "ID of game to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Game"
        "400":
          description: "Invalid ID supplied"
        "403":
          description: "Forbidden access"
        "404":
          description: "Game not found"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /game/treasures:
    post:
      tags:
      - "game"
      summary: "uploads a treasure within a game"
      description: ""
      operationId: "create_treasure"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "ID of game to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "treasure"
        description: "The treasure to be uploaded"
        required: true
        schema:
          $ref: "#/definitions/Treasure"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "Forbidden access"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /game/treasures/found:
    post:
      tags:
      - "game"
      summary: "uploads a treasure within a game"
      description: ""
      operationId: "treasure_found"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "ID of game to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "treasure"
        description: "The treasure to be uploaded"
        required: true
        schema:
          $ref: "#/definitions/FoundTreasure"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "Forbidden access"
      x-swagger-router-controller: "swagger_server.controllers.game_controller"
  /user:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "get_user_by_token"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "create_user"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "403":
          description: "Forbidden access"
        default:
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "delete_user"
      produces:
      - "application/json"
      parameters:
      - name: "userToken"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "userId"
        description: "The name that needs to be deleted"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "400":
          description: "Invalid userId supplied"
        "403":
          description: "Forbidden access"
        "404":
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
definitions:
  Area:
    type: "object"
    properties:
      centerCoordinates:
        type: "array"
        xml:
          name: "centerCoordinates"
          wrapped: true
        items:
          type: "number"
        maxItems: 2
      dimensions:
        type: "array"
        xml:
          name: "rectangleDimensions"
          wrapped: true
        items:
          type: "number"
        maxItems: 2
    xml:
      name: "area"
    example:
      centerCoordinates:
      - 6.02745618307040320615897144307382404804229736328125
      - 6.02745618307040320615897144307382404804229736328125
      dimensions:
      - 1.46581298050294517310021547018550336360931396484375
      - 1.46581298050294517310021547018550336360931396484375
  FoundTreasure:
    type: "object"
    properties:
      index:
        type: "number"
      proof:
        type: "string"
  Hint:
    type: "object"
    properties:
      imageUrl:
        type: "string"
      text:
        type: "string"
  Found:
    type: "object"
    properties:
      userId:
        type: "number"
      proof:
        type: "string"
  Treasure:
    type: "object"
    properties:
      location:
        type: "array"
        xml:
          name: "locationCoordinates"
          wrapped: true
        items:
          type: "number"
        maxItems: 2
      hint:
        $ref: "#/definitions/Hint"
      found:
        type: "array"
        items:
          $ref: "#/definitions/Found"
    xml:
      name: "treasure"
    example:
      found:
      - "{}"
      - "{}"
      hint: "{}"
      location:
      - 5.962133916683182377482808078639209270477294921875
      - 5.962133916683182377482808078639209270477294921875
  User:
    type: "object"
    required:
    - "rol"
    properties:
      _id:
        type: "string"
      username:
        type: "string"
      email:
        type: "string"
      rol:
        type: "string"
        enum:
        - "user"
        - "admin"
        - "jesucristo"
    xml:
      name: "User"
    example:
      _id: "_id"
      email: "email"
      rol: "user"
      username: "username"
  Game:
    type: "object"
    required:
    - "area"
    - "treasures"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
      winner:
        type: "string"
      description:
        type: "string"
      organizerId:
        type: "number"
      area:
        $ref: "#/definitions/Area"
      treasures:
        type: "array"
        xml:
          name: "treasures"
          wrapped: true
        items:
          $ref: "#/definitions/Treasure"
      active:
        type: "boolean"
        description: "game status"
    xml:
      name: "Game"
    example:
      area:
        centerCoordinates:
        - 6.02745618307040320615897144307382404804229736328125
        - 6.02745618307040320615897144307382404804229736328125
        dimensions:
        - 1.46581298050294517310021547018550336360931396484375
        - 1.46581298050294517310021547018550336360931396484375
      organizerId: 0.80082819046101150206595775671303272247314453125
      name: "name"
      description: "description"
      active: true
      _id: "_id"
      treasures:
      - found:
        - "{}"
        - "{}"
        hint: "{}"
        location:
        - 5.962133916683182377482808078639209270477294921875
        - 5.962133916683182377482808078639209270477294921875
      - found:
        - "{}"
        - "{}"
        hint: "{}"
        location:
        - 5.962133916683182377482808078639209270477294921875
        - 5.962133916683182377482808078639209270477294921875
